command          = atom? (<ws> atom)* <ws>*
<atom>           = global-options / target

<global-options> = global-option ( <ws> global-option )*
<global-option>  = help | version | dry-run | killer-run
help             = <'-h'> | <'--help'>
version          = <'-v'> | <'--version'>
dry-run          = <'--dryrun'> | <'--dry-run'>
killer-run       = <'--killer-run'> [ <ws> group-name ]
group-name       = #'[a-zA-Z0-9_:-]+'

target           = target-name / tag / preset
target-name      = glob
                 
tag              = <'tag:'> tag-name <'='> tag-value
tag-name         = #'[a-zA-Z0-9_-]+'
tag-value        = (<"'"> #"[^\']*" <"'">) | (<'"'> #'[^\"]*' <'"'>) | #'[a-zA-Z0-9_-]+'

preset            = default-selection
default-selection = <'--default-selection'>

<glob>           = #'[a-zA-Z0-9*?_][a-zA-Z0-9*?_-]*'
<ws>             = #'\s+'
